#include <Nebrix/Assets/AssetManager.h>
#include <Nebrix/Core/Assert.h>
#include <Nebrix/Core/Events.h>
#include <Nebrix/Core/GameLoop.h>
#include <Nebrix/Core/Input.h>
#include <Nebrix/Core/Log.h>
#include <Nebrix/ECS/Components.h>
#include <Nebrix/ECS/World.h>
#include <Nebrix/Math/Math.h>
#include <Nebrix/Physics/PhysicsSystem.h>
#include <Nebrix/Platform/Window.h>
#include <Nebrix/Renderer/Animation.h>
#include <Nebrix/Renderer/Camera2D.h>
#include <Nebrix/Renderer/Font.h>
#include <Nebrix/Renderer/Renderer.h>
#include <Nebrix/Renderer/SpriteSheet.h>
#include <Nebrix/UI/UI.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <format>
#include <vector>

#include "Maze.h"

using namespace nbx;

namespace
{

    constexpr uint32_t kWorldTiles = 100; // 100x100 grid = 10,000 tiles
    constexpr float kTileSize = 64.0f;
    constexpr uint32_t kAtlasCells = 4; // 4x4 sprite sheet

} // namespace

int main()
{
    Log::setLevel(LogLevel::Info);

    // TODO(nvidia-wayland): force X11 until the NVIDIA EGL Wayland presentation bug
    // (no buffer commits on this driver/Hyprland combo) is fixed system-side. The
    // engine itself defaults to Auto; run with NBX_PLATFORM=wayland to override.
    Window window({.title = "Nebrix Sandbox — 10k sprites",
                   .width = 1280,
                   .height = 720,
                   .vsync = true,
                   .platform = WindowProps::Platform::X11});
    if (!window.init())
        return 1;
    if (!Renderer::init())
        return 1;
    AssetManager::init();

    // Custom batch shader with hot reload (edit the files while running),
    // cached by the AssetManager. Falls back to the engine's internal shader
    // if the files are missing.
    Shader *shader =
        AssetManager::getShader("batch", "shaders/batch.vert", "shaders/batch.frag");
    if (shader)
        Renderer::setShader(shader);
    else
        NBX_LOG_WARN("Using engine's default batch shader");

    // Bitmap font for menus and HUD, baked from a vendored TTF. Without it the
    // sandbox skips the menu and runs the game directly.
    Font *font = AssetManager::getFont("mono32", "fonts/NotoSansMono-Regular.ttf", 32.0f);
    if (!font)
        NBX_LOG_WARN("Running without text: font failed to load");

    Renderer::setViewport(static_cast<int>(window.width()), static_cast<int>(window.height()));

    Camera2D camera(window.width(), window.height());
    camera.setPosition({kWorldTiles * kTileSize * 0.5f, kWorldTiles * kTileSize * 0.5f});

    // Real PNG assets from disk, cached by the AssetManager. The tile sheet is
    // generated by sandbox/assets/generate_assets.py; SpriteSheet is a
    // non-owning grid view over the manager-owned texture.
    const SpriteSheet tileset(AssetManager::getTexture("textures/tileset.png").id(),
                              kAtlasCells, kAtlasCells, kTileSize, kTileSize);

    // Tile index -> sprite cell; Tilemap::tiles entries reference this table.
    std::array<Sprite, 16> tileSprites;
    for (uint32_t i = 0; i < tileSprites.size(); ++i)
        tileSprites[i] = tileset.sprite(i);

    // ECS world: player + one entity holding the tilemap.
    World world;

    const Entity player = world.createEntity();
    world.add<Transform>(player, {.position = {96.0f, 96.0f}, .scale = {48.0f, 48.0f}});
    const Sprite playerSprite =
        Sprite::fullTexture(AssetManager::getTexture("textures/player.png").id(), 48.0f, 48.0f);
    world.add<Sprite>(player, playerSprite);
    world.add<Velocity>(player, {});
    world.add<Collider>(player, Collider::fromScale({48.0f, 48.0f}));
    world.add<Player>(player, {.previous = {96.0f, 96.0f}});

    // Walk cycle from the generated strip: 4 frames, frame 0 is the idle pose.
    const SpriteSheet walkSheet(AssetManager::getTexture("textures/player_walk.png").id(), 4,
                                1, 48.0f, 48.0f);
    std::vector<Sprite> walkFrames;
    for (uint32_t i = 0; i < walkSheet.cellCount(); ++i)
        walkFrames.push_back(walkSheet.sprite(i));
    world.add<Animation>(player, {.frames = walkFrames, .fps = 8.0f});

    // Fully-connected maze (recursive backtracker, deterministic seed): every
    // carved cell is reachable, so the player can roam (the old checkerboard
    // of 2x2 blocks trapped the player in a 128px square).
    Tilemap tilemap = buildMaze(kWorldTiles, kTileSize);

    const Entity tilemapEntity = world.createEntity();
    world.add<Transform>(tilemapEntity, {});
    world.add<Tilemap>(tilemapEntity, std::move(tilemap));

    NBX_LOG_INFO("World ready: {} entities (1 player + 1 tilemap {}x{})", world.entityCount(),
                 kWorldTiles, kWorldTiles);

    // Physics: broadphase cell = 128px (two tile widths).
    PhysicsSystem physics;
    physics.setCellSize(128.0f);
    AnimationSystem animations;

    // Action mapping: the game logic refers to semantic actions, not raw keys.
    Input::mapAction("MoveLeft", {Key::A, Key::Left});
    Input::mapAction("MoveRight", {Key::D, Key::Right});
    Input::mapAction("MoveUp", {Key::W, Key::Up});
    Input::mapAction("MoveDown", {Key::S, Key::Down});
    Input::mapAction("ToggleCulling", {Key::C});
    Input::mapAction("ZoomIn", {Key::Equal, Key::KeyPadAdd});
    Input::mapAction("ZoomOut", {Key::Minus, Key::KeyPadSubtract});

    GameLoop loop;
    loop.setFixedTimestep(1.0 / 30.0);
    loop.setFrameCap(60);

    window.setEventCallback([&](const Event &event)
                            {
        if (event.type == Event::Type::Quit) {
            loop.stop();
        } else if (event.type == Event::Type::WindowResized) {
            Renderer::setViewport(event.data1, event.data2);
            camera.setViewportSize(static_cast<uint32_t>(event.data1),
                                   static_cast<uint32_t>(event.data2));
        } });

    constexpr float kWorldSize = kWorldTiles * kTileSize;

    // Starts in the menu when text is available; the sim stays frozen there.
    bool inMenu = (font != nullptr);

    loop.setFixedUpdateFn([&](double fixedDt)
                          {
        if (inMenu)
            return; // frozen while the menu is up
        const float dt = static_cast<float>(fixedDt);

        float dx = (Input::isActionDown("MoveRight") ? 1.0f : 0.0f) -
                   (Input::isActionDown("MoveLeft") ? 1.0f : 0.0f);
        float dy = (Input::isActionDown("MoveDown") ? 1.0f : 0.0f) -
                   (Input::isActionDown("MoveUp") ? 1.0f : 0.0f);
        math::vec2 direction(dx, dy);
        const float length = std::sqrt(direction.x * direction.x + direction.y * direction.y);
        if (length > 0.0f)
            direction = direction * (1.0f / length);

        for (auto [entity, player, transform, velocity, animation] :
             world.view<Player, Transform, Velocity, Animation>()) {
            (void)entity;
            player.previous = transform.position;
            velocity.value = length > 0.0f ? direction * player.speed : math::vec2{};
            if (length > 0.0f)
                transform.rotation = std::atan2(direction.y, direction.x);
            // Walk cycle plays while moving; stopping resets to frame 0 (idle).
            animation.playing = length > 0.0f;
            if (!animation.playing)
            {
                animation.timer = 0.0f;
                animation.index = 0;
            }
        }

        // Advance all animations, then move + resolve against solid walls
        // (axis-separated, grid broadphase).
        animations.update(world, dt);
        physics.step(world, dt);

        // Defensive world-bounds clamp (walls already cover most of the edge).
        for (auto [entity, player, transform] : world.view<Player, Transform>()) {
            (void)entity;
            (void)player;
            transform.position.x = std::clamp(transform.position.x, 32.0f, kWorldSize - 32.0f);
            transform.position.y = std::clamp(transform.position.y, 32.0f, kWorldSize - 32.0f);
        } });

    bool cullingEnabled = true;
    if (const char *culling = std::getenv("NEBRIX_CULLING"))
        cullingEnabled = std::string_view(culling) != "0";
    float targetZoom = 1.0f;
    uint64_t frameCounter = 0;

    loop.setUpdateFn([&](double dt)
                      {
        window.pollEvents();
        ui::beginFrame();
        if (shader && shader->update(dt)) {
            // Shader reloaded; Renderer keeps using the same Shader object.
            NBX_LOG_INFO("Shader hot-reloaded");
        }

        static bool escWasDown = false;
        const bool escDown = Input::isKeyDown(Key::Escape);
        if (escDown && !escWasDown && !inMenu)
            inMenu = true;
        escWasDown = escDown;

        static bool cWasDown = false;
        const bool cDown = Input::isActionDown("ToggleCulling");
        if (cDown && !cWasDown)
            cullingEnabled = !cullingEnabled;
        cWasDown = cDown;

        if (Input::isActionDown("ZoomIn"))
            targetZoom = std::clamp(targetZoom * 1.02f, 0.25f, 4.0f);
        if (Input::isActionDown("ZoomOut"))
            targetZoom = std::clamp(targetZoom / 1.02f, 0.25f, 4.0f);

        if (!inMenu)
        {
            camera.setZoom(camera.zoom() + (targetZoom - camera.zoom()) * 0.1f);
            camera.follow(world.get<Transform>(player).position, 8.0f, dt);
        } });

    loop.setRenderFn([&](const FrameStats &stats)
                     {
        Renderer::clear({0.09f, 0.10f, 0.13f, 1.0f});

        const float screenW = static_cast<float>(window.width());
        const float screenH = static_cast<float>(window.height());
        const math::mat4 screenProj = math::ortho(0.0f, screenW, screenH, 0.0f, -1.0f, 1.0f);

        if (inMenu && font)
        {
            // Menu pass in screen space: title + buttons, no world rendering.
            Renderer::beginFrame(screenProj);
            const float cx = screenW * 0.5f;
            const float cy = screenH * 0.5f;
            ui::labelCentered(*font, "NEBRIX", {0.0f, cy - 180.0f, screenW, 96.0f}, 3.0f,
                              {0.85f, 0.89f, 0.95f, 1.0f});
            ui::labelCentered(*font, "a 2d engine sandbox - maze - player - 10k tiles",
                              {0.0f, cy - 84.0f, screenW, 32.0f}, 1.0f,
                              {0.55f, 0.60f, 0.68f, 1.0f});
            if (ui::button(*font, "start", {cx - 150.0f, cy - 20.0f, 300.0f, 64.0f}, "START",
                           1.25f, {0.16f, 0.19f, 0.24f, 1.0f}, {0.37f, 0.51f, 0.67f, 1.0f},
                           {1.0f, 1.0f, 1.0f, 1.0f}))
            {
                inMenu = false;
                NBX_LOG_INFO("Starting game");
            }
            if (ui::button(*font, "quit", {cx - 150.0f, cy + 56.0f, 300.0f, 64.0f}, "QUIT",
                           1.25f, {0.16f, 0.19f, 0.24f, 1.0f}, {0.75f, 0.38f, 0.42f, 1.0f},
                           {1.0f, 1.0f, 1.0f, 1.0f}))
                loop.stop();
            ui::labelCentered(*font, "WASD / arrows move - +/- zoom - C culling - ESC menu",
                              {0.0f, screenH - 48.0f, screenW, 32.0f}, 0.75f,
                              {0.55f, 0.60f, 0.68f, 1.0f});
            Renderer::endFrame();
        }
        else
        {
            Renderer::beginFrame(camera.viewProjection());

            const float interpolation = static_cast<float>(stats.interpolation);

            // Tilemap: only cells inside the camera's view (all 10k when culling is off).
            for (auto [entity, tilemap, mapTransform] : world.view<Tilemap, Transform>()) {
                (void)entity;
                const float originX = mapTransform.position.x;
                const float originY = mapTransform.position.y;
                const math::vec2 viewMin = camera.position() -
                                           math::vec2(camera.viewWidth() * 0.5f, camera.viewHeight() * 0.5f);
                const math::vec2 viewMax = camera.position() +
                                           math::vec2(camera.viewWidth() * 0.5f, camera.viewHeight() * 0.5f);
                int32_t minX = 0;
                int32_t minY = 0;
                int32_t maxX = static_cast<int32_t>(tilemap.width) - 1;
                int32_t maxY = static_cast<int32_t>(tilemap.height) - 1;
                const bool visible =
                    !cullingEnabled ||
                    tilemap.cellRange(viewMin.x - originX, viewMin.y - originY, viewMax.x - originX,
                                      viewMax.y - originY, minX, minY, maxX, maxY);
                if (!visible)
                    continue;
                for (int32_t cy = minY; cy <= maxY; ++cy) {
                    for (int32_t cx = minX; cx <= maxX; ++cx) {
                        const math::vec2 center(originX + (static_cast<float>(cx) + 0.5f) * tilemap.tileSize,
                                                originY + (static_cast<float>(cy) + 0.5f) * tilemap.tileSize);
                        Renderer::drawQuad({.position = center, .scale = {tilemap.tileSize, tilemap.tileSize}},
                                           tileSprites[tilemap.indexAt(static_cast<uint32_t>(cx),
                                                                        static_cast<uint32_t>(cy))]);
                    }
                }
            }

            // Player: interpolated between the previous and current fixed step.
            for (auto [entity, player, transform, sprite] : world.view<Player, Transform, Sprite>()) {
                (void)entity;
                Renderer::drawQuad({.position = math::lerp(player.previous, transform.position,
                                                           interpolation),
                                    .rotation = transform.rotation,
                                    .scale = transform.scale},
                                   sprite);
            }

            Renderer::endFrame();

            // HUD pass in screen space: fps + controls hint.
            Renderer::beginFrame(screenProj);
            ui::panel({10.0f, 10.0f, 340.0f, 88.0f}, {0.05f, 0.06f, 0.08f, 0.75f});
            if (font)
            {
                ui::label(*font, std::format("fps {}", stats.fps), {22.0f, 20.0f}, 0.75f,
                          {1.0f, 1.0f, 1.0f, 1.0f});
                ui::label(*font, "WASD move - ESC menu", {22.0f, 52.0f}, 0.75f,
                          {0.65f, 0.70f, 0.78f, 1.0f});
            }
            Renderer::endFrame();
        }
        window.swapBuffers();

        if (++frameCounter % 60 == 0) {
            const Renderer::Stats& renderStats = Renderer::stats();
            NBX_LOG_INFO("fps={} quads={} drawCalls={} culling={}", stats.fps,
                         renderStats.quadCount, renderStats.drawCalls, cullingEnabled);
        } });

    NBX_LOG_INFO("Starting game loop (move: WASD, zoom: +/- , culling: C)");
    loop.run();
    NBX_LOG_INFO("Game loop ended");

    Renderer::shutdown();
    // Cached GL resources (textures, shaders) must die while the context lives.
    AssetManager::shutdown();
    window.shutdown();
    return 0;
}